trigger:
- master
stages:
 - stage: Deploy_stage
   displayName: Deploy_stage
   jobs:
    - deployment:
      environment: Chat-app-env
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Npm@1
              inputs:
                command: 'install'
                workingDir: '/var/www/html/chat-app-azure'
                verbose: true