trigger:
- master
  
stages:
 - stage: Deploy_stage
   displayName: Deploy_stage
   jobs:
    - deployment:
      environment: Chat-app-env
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  sudo npm install
                  sudo npm start
                  #sudo npm run test --if-present
