trigger:
- master
  
stages:
 - stage: Deploy_stage
   displayName: Deploy_stage
   jobs:
    - deployment:
      environment: Chat-app-env
      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  cd /var/www/html/testingAzure
                  git pull
                  npm install
                  npm run build --if-present
                  npm run test --if-present
